version: '3.4'
services:
  orocommerce:
    restart: always
    image: zhex900/ewhale:1
    ports:
      - "80:80"
    container_name: ewhale
    environment:
      AWS_KEY: ''
      AWS_SECRET: '+'
      AWS_REGION: 'eu-west-2'
      APP_DB_DRIVER: pdo_mysql
      APP_DB_HOST: ewhale-db.cpvplciobhuv.eu-west-2.rds.amazonaws.com
      APP_DB_NAME: ewhale
      APP_DB_PASSWORD:
      APP_DB_PORT: 3306
      APP_DB_USER: ewhale
      APP_HOSTNAME:
      APP_IS_INSTALLED: 'true'
      APP_MAILER_TRANSPORT: smtp
      APP_MAILER_HOST: email-smtp.eu-west-1.amazonaws.com
      APP_MAILER_PORT: 587
      APP_MAILER_ENCRYPTION: tls
      APP_MAILER_USER:
      APP_MAILER_PASSWORD: '/+%'
      APP_SECRET: 123456789
      APP_WEBSOCKET_BACKEND_PORT: 8080
      APP_WEBSOCKET_FRONTEND_PORT: 3088
      CMD_INIT_AFTER:
      CMD_INIT_BEFORE:
      CMD_INIT_CLEAN:
      CMD_INIT_INSTALLED: 'true'